### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by wsilverio** [luz-ciencia-emocao/jardim#1]
### Jardim: to-do list
- [ ] Esquemático
- [ ] Firmware
- [ ] Compra dos componentes
- [ ] Protótipo em placa perfurada/protoboard
- [ ] Teste do protótipo
- [ ] Layout da placa
- [ ] Confecção da placa
- [ ] Teste elétrico da placa
- [ ] Montagem dos componentes
- [ ] Documentação/Relatório
